on:
  push:
    tags:
    - '*-*-*'

name: Create release draft

jobs:
  build:
    name: Create release from tag
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: use node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: download dependencies
        run: npm ci

      - name: create release tarball
        run: ./.github/build-release.sh

      - name: create new release
        uses: softprops/action-gh-release@v1
        with:
          files: oc-editor-*.tar.gz
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
